language: node_js
node_js:
- '0.10'
notifications:
  email: false
branches:
  only:
    - master
env:
  global:
    secure: e9OnEboDTlpKgJYA9uDZL2Hp8Rt2z+wED1cfQe2LKZg6BteOkOBTfsy4cYfhfTJJKBZLw/GTbi5HnmUAJGWYTlAVUg23e/kamlU+ACl0GfKx5Ue+Tj2CMgbweoTvrpZRBrfYwKSZfH0Cc81bp4D+QPdlO9xMl5Agu5Sv8WI3U4g=
before_script:
- git config --global user.email "appium-ci@appium.com"
- git config --global user.name "appium-ci"
- echo "https://${GH_TOKEN}:@github.com" > ${HOME}/.git-credentials
- git config credential.helper "store --file=${HOME}/.git-credentials"
- git remote set-url --push origin $(git config --get remote.origin.url | sed s/git:/https:/)
- git config --global push.default simple
- git remote -v

- echo "https://${GH_TOKEN}:@github.com" > ${HOME}/.git-credentials
- git config credential.helper 'store --file=${HOME}/.git-credentials'
- git remote set-url --push origin https://github.com/sebv/experiment.git 

script:
- git branch -f ci
- git checkout ci
- date > current.txt
- git add current.txt
- git commit -a -m "changing current time"
- git push -f origin ci:ci

