language: node_js
node_js:
- '0.10'
notifications:
  email: false
branches:
  only:
    - master
env:
  global:
    secure: e9OnEboDTlpKgJYA9uDZL2Hp8Rt2z+wED1cfQe2LKZg6BteOkOBTfsy4cYfhfTJJKBZLw/GTbi5HnmUAJGWYTlAVUg23e/kamlU+ACl0GfKx5Ue+Tj2CMgbweoTvrpZRBrfYwKSZfH0Cc81bp4D+QPdlO9xMl5Agu5Sv8WI3U4g=
before_script:
- mkdir ~/.git
- echo "https://${GH_TOKEN}:@github.com" > ~/.git/credentials
- git config credential.helper 'store --file=~/.git/credentials'
- git remote set-url --push origin https://github.com/sebv/experiment.git 
# - git remote set-url --push origin https://${GH_TOKEN}:@github.com/sebv/experiment.git 

script:
- git remote -v
- git tag ci-$TRAVIS_BUILD_NUMBER
- git push --tags
